# Section 1. Basics of Python

#### Instructor: Pierre Biscaye

The content of this notebook draws on material from UC Berkeley's D-Lab Python Fundamentals [course](https://github.com/dlab-berkeley/Python-Fundamentals).

### Sections
1. Variables/objects
2. Variable types
3. Indexing

# 1. Python basics: objects/variables

Python is an *object-oriented* language. You define objects or variables and assign them values, and then conduct operations on those objects. 

Python defines a variety of object types. Today we will introduce you to some basic important ones.

*   Variables are names that you assign to values so you can recall them later. 
*   In Python the `=` symbol assigns the value on the right to the name on the left.
*   The variable or object is created when a value is assigned to it.

In [1]:
a=1
a

1

In [2]:
# order matters
2=b

SyntaxError: cannot assign to literal (2524607509.py, line 2)

You might have noticed the pound sign `#` in the code cell above. 
These indicate **comments**, meaning that line of your code won't run.
Comments are extremely helpful for making code readable and clear.

### Variable names:

*   cannot start with a digit
*   cannot contain spaces, quotation marks, or other punctuation
*   *may* contain an underscore (typically used to separate words in long variable names)
*   Underscores at the start like `__pierres_real_age` have a special meaning
    so we won't do that until we understand the convention.


In [3]:
2day='today'

SyntaxError: invalid syntax (1971134185.py, line 1)

In [4]:
first_name='Pierre'

### Python is case-sensitive.

*   Python thinks that upper- and lower-case letters are different,
    so `Name` and `name` are different variables.
*   There are conventions around using upper-case letters at the start of variable names
    so we will use lower-case letters for now.

### Use meaningful variable names.

*   Python doesn't care what you call variables as long as they obey the rules
    (alphanumeric characters and the underscore).
*   That said, don't use variable names that refer to existing variables and functions in Python (e.g., `print`, `sum`, `str`).
*   Use meaningful variable names to help other people understand what the program does.
*   The most important "other person" is your future self.
*   Variables defined in one cell exist/persist in all following cells; meaningful names help
    remind you what you've created and what they represent.
*   Notebook cells are just a way to organize a program:
    as far as Python is concerned,
    all of the source code is one long set of instructions.                             

In [5]:
flabadab = 35
print(first_name, 'is', flabadab, 'years old')

Pierre is 35 years old


### Displaying values

You can call a variable directly, or use `print` to display values.

*   Python has a built-in function called `print` that prints things as text.
*   Call the function (i.e., tell Python to run it) by using its name.
*   Provide values to the function (e.g., things to print) in parentheses.
*   `print` automatically puts a single space between items to separate them.
*   And wraps around to a new line at the end.

In [6]:
age=35
print(first_name, 'is', age, 'years old')

Pierre is 35 years old


In [7]:
# You do not always need to use print(), but if you do not it will only display the last item you call
age
first_name

'Pierre'

In [8]:
print(age)
print(first_name)

35
Pierre


Variables must be created before they are used.

If a variable doesn't exist yet, or if the name has been mis-spelled,
    Python reports an error.

In [9]:
print(first_name)
print(last_name)

Pierre


NameError: name 'last_name' is not defined

The last line of an error message is usually the most informative.
  
We will look at error messages in detail later.

### Key points

1. "Use variables to store values."
2. "Use `print` to display values."
3. "Variables persist between cells."
4. "Variables must be created before they are used."
5. "Python is case-sensitive."
6. "Variables can be used in calculations."
7. "Use meaningful variable names."

<a id='type'></a>

# 2 Variable Types

Every value has a type.

*   Every value in a program has a specific type.
*   Integer (`int`): counting numbers like 3 or -512.
*   Floating point number (`float`): fractional numbers like 3.14159 or -2.5.
    *   Integers are used to count, floats are used to measure.
*   Character string (usually just called "string", `str`): text.
    *   Written in either single quotes or double quotes (as long as they match).
    *   The quotation marks aren't printed when the string is displayed.

Use the built-in function `type` to find the type of a value.

*   Works on variables as well.
*   But remember: the *value* has the type --- the *variable* is just a label.

In [10]:
# Q: what is the type of the number 1?
type(1)

int

In [11]:
# Q: what is the type of 'Pierre'?
type('Pierre')

str

In [12]:
# Q: What is the type of the object a we created above?
type(a) 

int

In [13]:
# Q: What is the type of a = '1'?
a='1'
type(a)

str

In [14]:
# Q: What is the type of True?
type(True)

bool

## Working with variables

Types control what operations can be done on values.

In [16]:
print(5-3)

2


In [17]:
print('hello' - 'h')

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [18]:
# "Adding" character strings concatenates them.
print('hello' + ', how are you?')

hello, how are you?


In [19]:
# Multiplying a character string by an integer replicates it.
print('hello'*5)

hellohellohellohellohello


In [20]:
# The built-in function len counts the number of characters in a string.
len('hello')

5

In [21]:
# numbers don't have a length
len(34)

TypeError: object of type 'int' has no len()

In [22]:
# cannot add numbers and strings
print(1 + '2')

TypeError: unsupported operand type(s) for +: 'int' and 'str'

*   Not allowed because it's ambiguous: should `1 + '2'` be `3` or `'12'`?
*   Use the name of a type as a function to convert a value to that type.
*   This **type conversion** is also called **casting** a value.

In [23]:
print(1 + int('2'))
print(str(1) + '2')

3
12


In [24]:
# Integers and floating-point numbers can be mixed in arithmetic.
# Python automatically converts integers to floats as needed.
print('three squared is', 3.0 ** 2)
print('half that is', (3.0 ** 2) / 2.0)

three squared is 9.0
half that is 4.5


In [30]:
# math with numbers
print(age+3)
print(age/2)
print(age**2)
year=2024
print('birth year is ', year-age)

38
17.5
1225
birth year is  1989


In [1]:
# Working with strings
first_name = "Pierre"
last_name = "Biscaye"
full_name = first_name + " " + last_name  # this is called concatenating
print(full_name)


Pierre Biscaye


Strings are made up of sub-strings

* You can think of strings as a *sequence* of smaller strings or characters. 
* We can access a piece of that sequence using `[]`.
* If you want a range (or "slice") of a sequence, you get everything before the second index:

In [ ]:
print(full_name[1])
print(full_name[0])
print(full_name[0:6])
print(full_name[1:9])
print(full_name[:5])
print(full_name[8:])

## Ordered Data Structures

**Data structures** allow us to organize data. A list is one such data structure. It is a collection of ordered items. Use a list when you want to keep a bunch of items in one spot.

### Lists

We specify a list with square brackets: `[]` and commas separating each entry in the list.

They usually contain homogeneous items - all of the same type - but not necessarily.

In [44]:
a = [5, 7, 9]
type(a)

list

In [26]:
# notice that we have overwritten the object `a'
# most objects we create are 'mutable', meaning they can be changed
# other built-in objects such as numbers, tuples, and strings are 'immutable'

In [45]:
# replace the first value of the list a
print(a)
a[0]=1
print(a)

[5, 7, 9]
[1, 7, 9]


In [28]:
# Try it with a string
str='string'
print(str[0])
str[0]='j'

s


TypeError: 'str' object does not support item assignment

In [3]:
# Lists may contain different types of objects
cities = ['Clermont-Ferrand', 'Berkeley', 7]
type(cities)

list

In [4]:
# len() gives the number of items in a list
len(cities)

3

In [ ]:
# What is a + a?
a+a

In [ ]:
# Make an empty list using []
empty=[]

### Key points

- "Every value has a type."
- "Use the built-in function `type` to find the type of a value."
- "Types control what operations can be done on values."
- "Strings can be added and multiplied."
- "Strings have a length (but numbers don't)."
- "Must convert numbers to strings or vice versa when operating on them."
- "Can mix integers and floats freely in operations."
- "Variables only change value when something is assigned to them."

# 3. Indexing

In [3]:
# Indexing: What is the first element of list a?
# python indexing starts with 0!
a=[1,4,7]
b=['1','2','3','Go!']
a[0]

1

In [ ]:
# What is the third element of list a?
a[2]

In [ ]:
# What is the third element of list a? Can also start from the end
a[-1]

In [4]:
# Change elements in the list
b[0]=2
b[3]='True'
b

[2, '2', '3', 'True']

We can also get multiple items from a list. We specify the start index and the end index, separated by a colon `[start:stop]`. 

The colon indicates that you want to access the item between the two endpoints. If one side of the colon is empty, it indicates using one end of the list as the starting or ending points. 

Note that the first index is *included*, while the second is *excluded*.

In [27]:
country_list = ['Ethiopia', 'Canada', 'Thailand', 'Denmark', 'Japan']
print(country_list[1:3])
print(country_list[2:4])
print(country_list[3:])
print(country_list[:-2])

['Canada', 'Thailand']
['Thailand', 'Denmark', 'Japan']
['Japan']
['Ethiopia', 'Canada', 'Thailand']


In [ ]:
# Lists’ values can be replaced by assigning to specific indices.
country_list[0] = "Iran"
print('Country List is now:', country_list)

In [7]:
# Indexing with arrays (matrices)
import numpy as np
A = np.array(np.arange(16)).reshape((4, 4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [8]:
# Get second column
A[:,1]

array([ 1,  5,  9, 13])

In [9]:
# Get the first row
A[0,:]

array([0, 1, 2, 3])

In [10]:
# Get row 2 column 1 value
A[1,0]

4

In [11]:
# Selecting multiple rows at a time: [1,3] will show the second and fourth rows:
A[[1,3]]

array([[ 4,  5,  6,  7],
       [12, 13, 14, 15]])

In [12]:
# To select the first and third columns: 
# [0,2]- as the second argument in the square brackets. Then supply the first argument : which selects all rows.
A[:,[0,2]]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14]])

In [15]:
# Now, suppose that we want to select the submatrix made up of the second and fourth rows 
# as well as the first and third columns.
# will this work?
A[[1,3],[0,2]]

array([ 4, 14])

In [18]:
# Using slices
A[1:4:2,0:3:2]

array([[ 4,  6],
       [12, 14]])

### Boolean indexing

A *boolean* is a type equals either `True` (=1) or `False` (=0). The next line creates a vector of 0's of length equal to the first dimension of `A`. We define the zeros as type bool, meaning they take a value of False.

In [21]:
keep_rows = np.zeros(A.shape[0], bool)
keep_rows

array([False, False, False, False])

In [24]:
# now set the second and last element to true
keep_rows[[1,3]] = True
keep_rows

array([False,  True, False,  True])

In [25]:
# also works with 1
keep_rows[2] = 1
keep_rows

array([False,  True,  True,  True])

### Dictionaries

Another type of ordered structure.

In [1]:
# Dictionaries have key-value pairs
d = {'name': 'Pierre Biscaye',
    'department': 'CERDI',
    'year': 1}

In [2]:
# Indexing dictionaries
d['name']

'Pierre Biscaye'

In [ ]:
# Change keys and values in a dictionary
# Fill in your information
d['name']=
d['year']=
d

In [3]:
# Check the keys of a dictionary: .keys()
# This is an example of a method - more later
d.keys()

dict_keys(['name', 'department', 'year'])

In [4]:
# Check the values of a dictionary: .values()
d.values()

dict_values(['Pierre Biscaye', 'CERDI', 1])

# 4. Closing out a notebook

When you close your Jupyter notebook window, all of your values will be lost. But you can save your code for a later time.

Save up to this point (ctrl (command) s) and click 'Close and Shut down notebook' in the menu. This will take you back to the Jupyter dashboard.

Once all notebooks are shut down, to end the Jupyter server session, navigate to File-> Shut Down on the Dashboard. Then go back to the Anaconda Prompt or terminal and close it out. You may get a warning dialog box alerting you that Jupyter Notebook is still running, if you have not shut it down.